var annotated_dup =
[
    [ "CAboutDlg", "class_c_about_dlg.html", "class_c_about_dlg" ],
    [ "CChildView", "class_c_child_view.html", "class_c_child_view" ],
    [ "CDisplayTimer", "class_c_display_timer.html", "class_c_display_timer" ],
    [ "CEndScreen", "class_c_end_screen.html", "class_c_end_screen" ],
    [ "CGame", "class_c_game.html", "class_c_game" ],
    [ "CGameObject", "class_c_game_object.html", "class_c_game_object" ],
    [ "CGameObjectVisitor", "class_c_game_object_visitor.html", "class_c_game_object_visitor" ],
    [ "CPlayer", "class_c_player.html", "class_c_player" ],
    [ "Cproject1App", "class_cproject1_app.html", "class_cproject1_app" ],
    [ "CRedPen", "class_c_red_pen.html", "class_c_red_pen" ],
    [ "CScoreBoard", "class_c_score_board.html", "class_c_score_board" ],
    [ "CTimer", "class_c_timer.html", "class_c_timer" ],
    [ "CUMLAttribute", "class_c_u_m_l_attribute.html", "class_c_u_m_l_attribute" ],
    [ "CUMLClass", "class_c_u_m_l_class.html", "class_c_u_m_l_class" ],
    [ "CUMLComponent", "class_c_u_m_l_component.html", "class_c_u_m_l_component" ],
    [ "CUMLDisplay", "class_c_u_m_l_display.html", "class_c_u_m_l_display" ],
    [ "CUMLInheritance", "class_c_u_m_l_inheritance.html", "class_c_u_m_l_inheritance" ],
    [ "CUMLInherited", "class_c_u_m_l_inherited.html", "class_c_u_m_l_inherited" ],
    [ "CUMLName", "class_c_u_m_l_name.html", "class_c_u_m_l_name" ],
    [ "CUMLOperation", "class_c_u_m_l_operation.html", "class_c_u_m_l_operation" ],
    [ "CUMLPiece", "class_c_u_m_l_piece.html", "class_c_u_m_l_piece" ],
    [ "CUMLPieceEmitter", "class_c_u_m_l_piece_emitter.html", "class_c_u_m_l_piece_emitter" ],
    [ "CUmlVisitor", "class_c_uml_visitor.html", "class_c_uml_visitor" ],
    [ "CXMLReader", "class_c_x_m_l_reader.html", "class_c_x_m_l_reader" ]
];